### ISSUE TITLE
[feat] 유저가 키워드들을 선택하여 좌석 추천과 성향을 추천받을 수 있다.

### ISSUE THREAD

**Issue by juuuunny** [KUSITMS-30th-TEAM-A/backend#11]
### 📝 Description

- 구장별 좌석 추천을 조회할 수 있다.

---

### 📝 Todo

- [x] Enum에 구장별 구역 정보 저장하기
- [x] 클라이언트 측으로부터 구장과 키워드를 받을 시 해당 유저의 성향과 구장 구역을 최대 3가지 추천을 해준다.
- [x] 입력받은 키워드들로부터 유저 성향을 파악할 수 있다.
