### ISSUE TITLE
[feat] : 에러 처리를 추가한다

### ISSUE THREAD

**Issue by bbbang105** [KUSITMS-30th-TEAM-A/backend#35]
### 📝 Description

- 에러 처리를 추가한다

---

### 📝 Todo

- [x] DataIntegrityViolationException 처리 (데이터베이스 제약 조건 위반)
- [x] HttpMessageNotReadableException 처리 (잘못된 JSON 형식)
- [x] MissingRequestHeaderException 처리 (필수 헤더가 누락된 경우)
- [x] NullPointerException 처리
- [x] NumberFormatException 처리
- [x] IndexOutOfBoundsException 처리
